@clientId=944142e9-20c0-4102-9bb8-d19f25ae7237
@secret=8d9696f32d13d1cdfc309f9be24814c949636f96

@sandbox_url=http://localhost/enox/flow/enode"

### Get OAuth token
# @name tokenrequest
POST https://oauth.sandbox.enode.io/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}}:{{secret}}

grant_type=client_credentials

###

@token={{tokenrequest.response.body.access_token}}
@tokenType={{tokenrequest.response.body.token_type}}

###

@userId=1ab23cd54

### Create link session for user
# @name linkrequest
POST https://enode-api.sandbox.enode.io/users/{{userId}}/link HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "vendorType": "vehicle"
}

###

@linkURL = {{linkrequest.response.body.linkUrl}}

curl -i http://127.0.0.1:3000/enox/flow/enode/vehicles/a7e07299-18db-49f3-abe6-970d676e9ea8/charging \
-X POST \
-H "Authorization: Bearer 3Gfd2SkT6pS14uC4_PXPoh8V0YtLar_efjmE_WkJCZA.8aRo3-m4D0aXNrW8PN55X6wlm38J0j3c0Byd42V2c_A" \
-H "Content-Type: application/json" \
-d '{
  "action": "START"
}'

curl -i http://127.0.0.1:3000/enox/flow/enode/users/link \
-X POST \
-H "Content-Type: application/json" \
-d '{
  "userId": "yauch",
  "vendor": "TESLA",
  "vendorType": "vehicle"
}'



curl -i https://enode-api.sandbox.enode.io/vehicles/a7e07299-18db-49f3-abe6-970d676e9ea8/charging \
-X POST \
-H "Authorization: Bearer 3Gfd2SkT6pS14uC4_PXPoh8V0YtLar_efjmE_WkJCZA.8aRo3-m4D0aXNrW8PN55X6wlm38J0j3c0Byd42V2c_A" \
-H "Content-Type: application/json" \
-d '{
  "action": "START"
}'